Repository Nexters/ziine-android, pull requests merged in 2025-01, with the labels that each got.

#2 [feat] Version Catalog 구성 (#1)
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#10 [chore] git hook pre-push 시기에 ktlint 체크하도록 스크립트 적용 (#9)
  .editorconfig
  app/build.gradle.kts
  app/src/androidTest/java/com/nexters/ziine/android/ExampleInstrumentedTest.kt
  app/src/main/java/com/nexters/ziine/android/MainActivity.kt
  app/src/main/java/com/nexters/ziine/android/ui/theme/Color.kt
  app/src/main/java/com/nexters/ziine/android/ui/theme/Theme.kt
  app/src/main/java/com/nexters/ziine/android/ui/theme/Type.kt
  app/src/test/java/com/nexters/ziine/android/ExampleUnitTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 창환🐗, chore

#13 [feat] app 모듈 기초 설정
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/nexters/ziine/android/MainActivity.kt
  app/src/main/kotlin/com/nexters/ziine/android/ZiineApplication.kt
  app/src/main/kotlin/com/nexters/ziine/android/initializer/TimberInitializer.kt
  app/src/main/kotlin/com/nexters/ziine/android/ui/theme/Color.kt
  app/src/main/kotlin/com/nexters/ziine/android/ui/theme/Font.kt
  app/src/main/kotlin/com/nexters/ziine/android/ui/theme/Theme.kt
  app/src/main/kotlin/com/nexters/ziine/android/ui/theme/Type.kt
  gradle/libs.versions.toml
Labels: 지훈🖥️, feat
