Repository Nexters/ziine-android, pull requests merged in 2025-02, with the labels that each got.

#21 [feat] debug, release 앱 분리 #19
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: 지훈🖥️, feat

#14 [feat] 화면 네비게이션 구성 #3
  .editorconfig
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/nexters/ziine/android/MainActivity.kt
  build.gradle.kts
  gradle/libs.versions.toml
  presentation/.gitignore
  presentation/build.gradle.kts
  presentation/consumer-rules.pro
  presentation/proguard-rules.pro
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/ic_launcher-playstore.png
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/MainActivity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/ZiineTopBar.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/MainNavController.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/MainTab.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/Route.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/TabController.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/ComponentPreview.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/DevicePreview.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ui/theme/Color.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ui/theme/Font.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ui/theme/Theme.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ui/theme/Type.kt
  presentation/src/main/res/drawable/ic_launcher_background.xml
  presentation/src/main/res/drawable/ic_launcher_foreground.xml
  presentation/src/main/res/font/pretendard_medium.otf
  presentation/src/main/res/font/pretendard_regular.otf
  presentation/src/main/res/font/pretendard_semi_bold.otf
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  presentation/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  presentation/src/main/res/mipmap-hdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  presentation/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
  presentation/src/main/res/xml/backup_rules.xml
  presentation/src/main/res/xml/data_extraction_rules.xml
  settings.gradle.kts
Labels: 지훈🖥️, feat

#22 [feat] data 모듈 생성 및 서버통신 기초 세팅 #11
  build.gradle.kts
  data/.gitignore
  data/build.gradle.kts
  data/consumer-rules.pro
  data/proguard-rules.pro
  data/src/main/java/com/nexters/ziine/android/data/di/RetrofitModule.kt
  data/src/main/java/com/nexters/ziine/android/data/httpClient/ResposeStateConvert.kt
  data/src/main/java/com/nexters/ziine/android/data/httpClient/dto/response/ErrorResponse.kt
  data/src/main/java/com/nexters/ziine/android/data/model/forpackage
  data/src/main/java/com/nexters/ziine/android/data/repository/forpackage
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 창환🐗, feat

#18 [feat] 스플래시 화면 구성 #4
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/MainActivity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/extensions/Activity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/splash/SplashActivity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/splash/SplashScreen.kt
  presentation/src/main/res/drawable/ic_dummy_splash.xml
  presentation/src/main/res/drawable/ziine_splash.png
  presentation/src/main/res/raw/splash.json
  presentation/src/main/res/values/splash.xml
  presentation/src/main/res/values/strings.xml
Labels: 지훈🖥️, feat

#26 [feat] Artworks(작품목록) 화면 구성 #15
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/nexters/ziine/android/ZiineApplication.kt
  data/src/main/java/com/nexters/ziine/android/data/di/RetrofitModule.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/MainActivity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworkItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/model/UiArtwork.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiState.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/NetworkImage.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/ArtworksPreviewParameterProvider.kt
  presentation/src/main/res/drawable/placeholder.png
Labels: 지훈🖥️, feat

#28 [feat] 작품 상세 화면 구성 #16
  app/src/androidTest/java/com/nexters/ziine/android/ExampleInstrumentedTest.kt
  app/src/test/java/com/nexters/ziine/android/ExampleUnitTest.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtistDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDetailItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDetailTopBar.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ContactLinks.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/EducationTags.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ExhibitionRecords.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/model/UiArtistDetail.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/model/UiArtworkDetail.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailUiState.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworkItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/model/UiArtist.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/model/UiArtwork.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/util/ObserveAsEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/NetworkImage.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/ZiineSnackbar.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/MainNavController.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/Route.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/TabController.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/ArtworkDetailPreviewParameterProvider.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/ArtworksPreviewParameterProvider.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/DevicePreview.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ui/theme/Theme.kt
  presentation/src/main/res/drawable/ic_arrow_back.xml
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/ic_contact.xml
  presentation/src/main/res/drawable/ic_instagram.png
  presentation/src/main/res/drawable/ic_multiply.xml
  presentation/src/main/res/drawable/ic_share.xml
  presentation/src/main/res/values/strings.xml
Labels: 지훈🖥️, feat

#34 [feat] 작품 등록 대기화면 구성 #23
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/util/Devices.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/util/ObserveAsEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/webViews/GeneralWebView.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/webViews/ZiineWebChromeClient.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/webViews/ZiineWebViewBridge.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/RegisterTopBar.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/RegisterArtworkActivity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/CompleteNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/CompleteScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/viewmodel/CompleteUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/viewmodel/CompleteUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/viewmodel/CompleteViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/navigation/RegisterArtWorkRoute.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/navigation/RegitsterArtWorkNavHost.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/PendingNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/PendingScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/model/UiPendingGuideItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/viewmodel/PendingUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/viewmodel/PendingUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/viewmodel/PendingViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/register/RegisterNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/register/RegisterScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/register/viewmodel/RegisterUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/register/viewmodel/RegisterUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/register/viewmodel/RegisterViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ui/theme/Theme.kt
  presentation/src/main/res/values/strings.xml
Labels: 창환🐗, feat

#36 [feat] 작품 목록, 상세 화면 API 연동 #33
  app/src/main/AndroidManifest.xml
  data/src/main/kotlin/com/nexters/ziine/android/data/di/RetrofitModule.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/httpClient/dto/response/ArtworkDetailResponse.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/httpClient/dto/response/ArtworkResponse.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/mapper/artwork/ArtworkDtoMapper.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/repository/DefaultArtworkRepository.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/service/ZiineService.kt
  domain/src/main/kotlin/com/nexters/ziine/android/domain/entity/Artwork.kt
  domain/src/main/kotlin/com/nexters/ziine/android/domain/entity/ArtworkDetail.kt
  domain/src/main/kotlin/com/nexters/ziine/android/domain/repository/ArtworkRepository.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtistDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/model/UiArtworkDetail.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailUiState.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksUiState.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/viewmodel/ArtworksViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/ZiineErrorDialog.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/mapper/artwork/ArtworkUiMapper.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/preview/ArtworkDetailPreviewParameterProvider.kt
  presentation/src/main/res/values/strings.xml
Labels: 지훈🖥️, feat, fix

#38 [feat] 작품 목록, 상세 화면 디테일 작업 #37
  app/src/main/AndroidManifest.xml
  gradle/libs.versions.toml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworkItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/LoadingIndicator.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/LottieImage.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/NetworkImage.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/component/ZiineErrorDialog.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/TabController.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/splash/SplashActivity.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/splash/SplashScreen.kt
  presentation/src/main/res/drawable/bottom_gradient.xml
  presentation/src/main/res/drawable/error_image.xml
  presentation/src/main/res/drawable/top_gradient.xml
  presentation/src/main/res/xml/network_security_config.xml
Labels: 지훈🖥️, feat

#40 [feat] 작품 목록, 상세 화면 디테일 작업 #37
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/nexters/ziine/android/initializer/FirebaseCrashlyticsInitializer.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/repository/DefaultArtworkRepository.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/service/ZiineService.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/CompleteScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/PendingScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/register/RegisterScreen.kt
  presentation/src/main/res/drawable/artwork_guide_1.png
  presentation/src/main/res/drawable/artwork_guide_2.png
  presentation/src/main/res/drawable/artwork_guide_3.png
  presentation/src/main/res/raw/artwork_register_completed.json
Labels: 지훈🖥️, feat

#41 [feat] 매거진 화면 구성 (#35)
  data/src/main/kotlin/com/nexters/ziine/android/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/httpClient/dto/response/MagazineResponse.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/mapper/magazine/MagazineDtoMapper.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/repository/DefaultMagazineRepository.kt
  data/src/main/kotlin/com/nexters/ziine/android/data/service/ZiineService.kt
  domain/src/main/kotlin/com/nexters/ziine/android/domain/entity/Magazine.kt
  domain/src/main/kotlin/com/nexters/ziine/android/domain/entity/Magazines.kt
  domain/src/main/kotlin/com/nexters/ziine/android/domain/repository/MagazineRepository.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/util/Devices.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/webViews/GeneralWebView.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/model/UiMagazine.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/viewModel/MagazineUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/viewModel/MagazineUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/viewModel/MagazineUiState.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/viewModel/MagazineViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazinedetail/MagazineDetailNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazinedetail/MagazineDetailScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazinedetail/viewmodel/MagazineDetailUiAction.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazinedetail/viewmodel/MagazineDetailUiEvent.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazinedetail/viewmodel/MagazineDetailViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/mapper/magazine/MagazineUiMapper.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/MainNavController.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/navigation/Route.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/CompleteScreen.kt
Labels: 창환🐗, feat

#44 [fix] 작품 상세 화면 ShareUrl 빈값으로 공유되는 문제 해결 #43
  app/build.gradle.kts
  data/src/main/kotlin/com/nexters/ziine/android/data/mapper/artwork/ArtworkDtoMapper.kt
  gradle/libs.versions.toml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtistDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDetailItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworkItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/mapper/artwork/ArtworkUiMapper.kt
Labels: 지훈🖥️, refactor, hotfix

#46 release v1.0.1
  app/build.gradle.kts
  data/src/main/kotlin/com/nexters/ziine/android/data/mapper/artwork/ArtworkDtoMapper.kt
  gradle/libs.versions.toml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/ZiineApp.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/ArtworkDetailScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtistDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDescription.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/component/ArtworkDetailItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworkdetail/viewmodel/ArtworkDetailViewModel.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworkItem.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksNavigation.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/mapper/artwork/ArtworkUiMapper.kt
Labels: 지훈🖥️, release, hotfix

#49 [fix] 공백 문자열(" ") 미적용 문제 해결 #48
  gradle/libs.versions.toml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/util/Devices.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/CompleteScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/PendingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 지훈🖥️, fix

#50 release v1.0.2
  gradle/libs.versions.toml
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/artworks/ArtworksScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/common/util/Devices.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/magazine/MagazineScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/complete/CompleteScreen.kt
  presentation/src/main/kotlin/com/nexters/ziine/android/presentation/registerArtwork/pending/PendingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: 지훈🖥️, fix, release
